import React from 'react';
import { X, Sparkles, Send, TrendingUp, TrendingDown, Target, Shield, Percent, Lightbulb, AlertTriangle } from 'lucide-react';
import type { TradeSignal } from '@/services/agent3.service';
import '@/styles/components/tradeProposal.css';

interface AISignalModalProps {
  isOpen: boolean;
  onClose: () => void;
  signal: TradeSignal | null;
  onProposeTrade: (signal: TradeSignal) => void;
}

export const AISignalModal: React.FC<AISignalModalProps> = ({
  isOpen,
  onClose,
  signal,
  onProposeTrade,
}) => {
  if (!isOpen || !signal) return null;

  const isBuy = signal.action === 'BUY';
  const isHold = signal.action === 'HOLD';
  const confidencePercent = Math.round((signal.confidence_score || 0) * 100);

  const actionBg = isHold
    ? 'rgba(148, 163, 184, 0.15)'
    : isBuy
    ? 'rgba(16, 185, 129, 0.15)'
    : 'rgba(239, 68, 68, 0.15)';

  const actionColor = isHold ? '#94a3b8' : isBuy ? '#34d399' : '#f87171';

  const strategyDisplayName =
    !signal.primary_strategy || signal.primary_strategy === 'None'
      ? 'No active strategy'
      : signal.primary_strategy;

  return (
    <div className="tp-modal-overlay" onClick={onClose} data-testid="ai-signal-modal-overlay">
      <div
        className="tp-modal-card"
        onClick={(e) => e.stopPropagation()}
        style={{ maxWidth: '540px' }}
        data-testid="ai-signal-modal-card"
      >
        {/* Header */}
        <div className="tp-modal-header">
          <div className="tp-header-title-group">
            <div className="tp-modal-title">
              <Sparkles size={20} color="#a855f7" />
              <span>AI Strategy Signal</span>
              <span className="tp-paper-badge">AGENT 3 OUTPUT</span>
            </div>
            <div className="tp-subtitle">
              Generated by Agent 3 Strategy Engine
            </div>
          </div>
          <button className="tp-close-btn" onClick={onClose} aria-label="Close modal">
            <X size={18} />
          </button>
        </div>

        <div className="tp-modal-body">
          {/* Symbol & Action Banner */}
          <div
            style={{
              background: 'rgba(15, 23, 42, 0.6)',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              borderRadius: 12,
              padding: '16px 20px',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}
          >
            <div>
              <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#f8fafc' }}>
                {signal.symbol}
              </div>
              <div style={{ fontSize: '0.8rem', color: isHold ? '#94a3b8' : '#a855f7', fontWeight: 600, marginTop: '2px' }}>
                {strategyDisplayName}
              </div>
            </div>

            <div
              style={{
                background: actionBg,
                color: actionColor,
                border: `1px solid ${actionColor}40`,
                padding: '6px 16px',
                borderRadius: 20,
                fontWeight: 800,
                fontSize: '0.95rem',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
              }}
              data-testid="signal-action-badge"
            >
              {isBuy ? <TrendingUp size={16} /> : isHold ? null : <TrendingDown size={16} />}
              <span>{signal.action}</span>
            </div>
          </div>

          {/* EXECUTABLE TRADE PARAMETERS (BUY / SELL ONLY) */}
          {!isHold && (
            <>
              <div className="tp-form-grid" style={{ gridTemplateColumns: 'repeat(3, 1fr)', marginTop: '0.5rem' }}>
                <div className="tp-metric-card">
                  <div className="tp-metric-label">
                    <Target size={12} color="#3b82f6" />
                    <span>Entry Price</span>
                  </div>
                  <div className="tp-metric-value" style={{ color: '#60a5fa' }}>
                    ${signal.entry_price.toFixed(2)}
                  </div>
                </div>

                <div className="tp-metric-card">
                  <div className="tp-metric-label">
                    <Shield size={12} color="#ef4444" />
                    <span>Stop Loss</span>
                  </div>
                  <div className="tp-metric-value" style={{ color: '#f87171' }}>
                    ${signal.stop_loss.toFixed(2)}
                  </div>
                </div>

                <div className="tp-metric-card">
                  <div className="tp-metric-label">
                    <TrendingUp size={12} color="#10b981" />
                    <span>Take Profit</span>
                  </div>
                  <div className="tp-metric-value" style={{ color: '#34d399' }}>
                    ${signal.take_profit.toFixed(2)}
                  </div>
                </div>
              </div>

              <div className="tp-form-grid" style={{ marginTop: '0.5rem' }}>
                <div className="tp-metric-card">
                  <div className="tp-metric-label">
                    <span>Risk / Reward</span>
                  </div>
                  <div className="tp-metric-value" style={{ color: '#fbbf24' }}>
                    1 : {(signal.risk_reward_ratio || 2.0).toFixed(1)}
                  </div>
                </div>

                <div className="tp-metric-card">
                  <div className="tp-metric-label">
                    <Percent size={12} color="#a855f7" />
                    <span>AI Confidence</span>
                  </div>
                  <div className="tp-metric-value" style={{ color: '#c084fc' }}>
                    {confidencePercent}%
                  </div>
                </div>
              </div>
            </>
          )}

          {/* HOLD CONFIDENCE ONLY CARD */}
          {isHold && (
            <div className="tp-form-grid" style={{ marginTop: '0.5rem' }}>
              <div className="tp-metric-card" style={{ gridColumn: 'span 2' }}>
                <div className="tp-metric-label">
                  <Percent size={12} color="#a855f7" />
                  <span>AI Confidence</span>
                </div>
                <div className="tp-metric-value" style={{ color: '#94a3b8' }}>
                  {confidencePercent}%
                </div>
              </div>
            </div>
          )}

          {/* Strategy Rationale */}
          {signal.reasons && signal.reasons.length > 0 && (
            <div
              style={{
                background: 'rgba(168, 85, 247, 0.05)',
                border: '1px solid rgba(168, 85, 247, 0.2)',
                borderRadius: 10,
                padding: '12px 16px',
                marginTop: '0.5rem',
              }}
            >
              <div style={{ fontSize: '0.8rem', fontWeight: 700, color: '#c084fc', display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px' }}>
                <Lightbulb size={14} />
                <span>Strategy Analysis Rationale</span>
              </div>
              <ul style={{ margin: 0, paddingLeft: '1.2rem', fontSize: '0.8rem', color: '#cbd5e1', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                {signal.reasons.map((reason, idx) => (
                  <li key={idx}>{reason}</li>
                ))}
              </ul>
            </div>
          )}

          {/* HOLD INFORMATION SECTION */}
          {isHold && (
            <div
              style={{
                background: 'rgba(245, 158, 11, 0.08)',
                border: '1px solid rgba(245, 158, 11, 0.25)',
                borderRadius: 10,
                padding: '14px 16px',
                marginTop: '0.75rem',
                display: 'flex',
                flexDirection: 'column',
                gap: '6px',
              }}
              data-testid="hold-opportunity-card"
            >
              <div
                style={{
                  fontSize: '0.85rem',
                  fontWeight: 800,
                  color: '#fbbf24',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                }}
              >
                <AlertTriangle size={16} color="#fbbf24" />
                <span>No Trade Opportunity</span>
              </div>
              <p style={{ margin: 0, fontSize: '0.8rem', color: '#cbd5e1', lineHeight: 1.4 }}>
                Agent 3 did not generate an executable BUY or SELL signal for this asset.
              </p>
              <div style={{ fontSize: '0.75rem', color: '#94a3b8', marginTop: '2px' }}>
                This asset is currently on HOLD. A Trade Proposal can only be created from a BUY or SELL signal.
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="tp-modal-footer">
          <button type="button" className="tp-btn-secondary" onClick={onClose}>
            Close
          </button>
          <button
            type="button"
            className="tp-btn-primary"
            disabled={isHold}
            onClick={() => {
              if (!isHold) onProposeTrade(signal);
            }}
            data-testid="propose-trade-btn"
          >
            <Send size={15} />
            <span>Propose Trade</span>
          </button>
        </div>
      </div>
    </div>
  );
};
